### ISSUE TITLE
Memory leak causes page file to grow very big on Windows

### ISSUE THREAD

**Issue by idroccolo** [0xboobface/ctbrec#13] opened 2018-08-13 23:30 UTC
Even if I set to save streams onto another disk (it hapens and it works) the app continues also to fill the system disk C and i have to constantly close and reopen the program. 

W10 64Bit, last Java available.

**Comment by 0xboobface** [comment] 2018-08-15 10:50
Do you know, what exactly is stored on your system disk?

**Comment by andreagdipaolo** [comment] 2018-08-15 16:05
I think i figured it out. Windows created a 40GB paging file on my disk C. I manually forced it to be 2.5GB (as I have 16GB of RAM) and now it doesn't grow unexpectedly. 
Anyway, sometimes the program does not merge the ts files, especially when some of them are corrupt. Sometimes it creates a playlist and a dummy merged .ts of 0KB.

**Comment by 0xboobface** [comment] 2018-08-16 16:39
Found a leak, which was caused by the filter bar. This will be fixed in the next version. I'm also going to restrict the heap size to 512MiB.

**Closed by 0xboobface** 2018-08-16 16:39 UTC
Labels: bug
