### ISSUE TITLE
Recording interrupted and not being resumed

### ISSUE THREAD

**Issue by reyaz006** [0xboobface/ctbrec#70] opened 2018-11-23 11:52 UTC
I've started noticing this since 1.10.0 I think.
Streams just stop being recorded to disk, the app still displays them as being recorded but nothing is being written. If I do Pause and Resume, it starts recording into new file again.

One error message I've noticed that may be related:

> 2018-11-23 03:44:04,017 ERROR [streaming] streamer [Streamer.java:247] Error sending packet to sink
> java.nio.channels.ClosedByInterruptException: null
> 	at java.base/java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:199)
> 	at java.base/sun.nio.ch.FileChannelImpl.endBlocking(FileChannelImpl.java:162)
> 	at java.base/sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:285)
> 	at org.taktik.mpegts.sinks.ByteChannelSink.send(ByteChannelSink.java:21)
> 	at org.taktik.mpegts.Streamer.internalStream(Streamer.java:245)
> 	at java.base/java.lang.Thread.run(Thread.java:834)
> 2018-11-23 03:44:04,018 DEBUG [Segment Merger Thread] c.r.d.MergedHlsDownload [MergedHlsDownload.java:288] Streamer finished

There are also a lot of lines like this before that error:
> 2018-11-23 03:46:33,302 WARN [Thread-312] c.r.d.MergedHlsDownload [MergedHlsDownload.java:180] Missed segments 7537 < 7544 in download for http*
> 2018-11-23 03:46:33,303 DEBUG [Thread-312] c.r.d.MergedHlsDownload [MergedHlsDownload.java:185] Loading missed segment 7537 for model http*
> 2018-11-23 03:46:43,584 DEBUG [Thread-312] c.r.d.MergedHlsDownload [MergedHlsDownload.java:185] Loading missed segment 7538 for model http*
> 2018-11-23 03:46:53,545 DEBUG [Thread-312] c.r.d.MergedHlsDownload [MergedHlsDownload.java:185] Loading missed segment 7539 for model http*
> 2018-11-23 03:47:02,862 DEBUG [Thread-312] c.r.d.MergedHlsDownload [MergedHlsDownload.java:185] Loading missed segment 7540 for model http*
> 2018-11-23 03:47:12,590 DEBUG [Thread-312] c.r.d.MergedHlsDownload [MergedHlsDownload.java:185] Loading missed segment 7541 for model http*
> 2018-11-23 03:47:22,989 DEBUG [Thread-312] c.r.d.MergedHlsDownload [MergedHlsDownload.java:185] Loading missed segment 7542 for model http*
> 2018-11-23 03:47:32,172 DEBUG [Thread-312] c.r.d.MergedHlsDownload [MergedHlsDownload.java:185] Loading missed segment 7543 for model http*

**Comment by reyaz006** [comment] 2018-11-23 12:35
I've tested previous versions now.
1.9.0: same problem.
1.8.0: no interruption, although the log reports something else:

> 2018-11-23 04:20:36,080 WARN [Thread-10] c.r.d.MergedHlsDownload [MergedHlsDownload.java:148] Missed segments 8564 < 8565 in download for http*
> 2018-11-23 04:20:50,869 WARN [Thread-10] c.r.d.MergedHlsDownload [MergedHlsDownload.java:148] Missed segments 8568 < 8573 in download for http*
> 2018-11-23 04:21:19,955 WARN [Thread-10] c.r.d.MergedHlsDownload [MergedHlsDownload.java:148] Missed segments 8576 < 8587 in download for http*
> 2018-11-23 04:22:21,641 WARN [Thread-10] c.r.d.MergedHlsDownload [MergedHlsDownload.java:148] Missed segments 8590 < 8617 in download for http*
> 2018-11-23 04:24:06,491 WARN [Thread-10] c.r.d.MergedHlsDownload [MergedHlsDownload.java:148] Missed segments 8620 < 8670 in download for http*
> 2018-11-23 04:24:45,055 WARN [buffering] o.t.m.s.BlockingMultiMTSSource [BlockingMultiMTSSource.java:51] Failed to fix continuity. MTSPacket probably invalid
> java.lang.NullPointerException: null
> 	at org.taktik.mpegts.sources.ContinuityFixer.fixContinuity(ContinuityFixer.java:88)
> 	at org.taktik.mpegts.sources.BlockingMultiMTSSource.nextPacketInternal(BlockingMultiMTSSource.java:49)
> 	at org.taktik.mpegts.sources.AbstractMTSSource.nextPacket(AbstractMTSSource.java:13)
> 	at org.taktik.mpegts.Streamer.fillBuffer(Streamer.java:267)
> 	at java.lang.Thread.run(Thread.java:748)
> 2018-11-23 04:24:45,056 WARN [buffering] o.t.m.s.BlockingMultiMTSSource [BlockingMultiMTSSource.java:51] Failed to fix continuity. MTSPacket probably invalid
> java.lang.NullPointerException: null
> 	at org.taktik.mpegts.sources.ContinuityFixer.fixContinuity(ContinuityFixer.java:88)
> 	at org.taktik.mpegts.sources.BlockingMultiMTSSource.nextPacketInternal(BlockingMultiMTSSource.java:49)
> 	at org.taktik.mpegts.sources.BlockingMultiMTSSource.nextPacketInternal(BlockingMultiMTSSource.java:52)
> 	at org.taktik.mpegts.sources.AbstractMTSSource.nextPacket(AbstractMTSSource.java:13)
> 	at org.taktik.mpegts.Streamer.fillBuffer(Streamer.java:267)
> 	at java.lang.Thread.run(Thread.java:748)
> 2018-11-23 04:24:45,056 WARN [buffering] o.t.m.s.BlockingMultiMTSSource [BlockingMultiMTSSource.java:51] Failed to fix continuity. MTSPacket probably invalid
> java.lang.NullPointerException: null
> 	at org.taktik.mpegts.sources.ContinuityFixer.fixContinuity(ContinuityFixer.java:88)
> 	at org.taktik.mpegts.sources.BlockingMultiMTSSource.nextPacketInternal(BlockingMultiMTSSource.java:49)
> 	at org.taktik.mpegts.sources.BlockingMultiMTSSource.nextPacketInternal(BlockingMultiMTSSource.java:52)
> 	at org.taktik.mpegts.sources.BlockingMultiMTSSource.nextPacketInternal(BlockingMultiMTSSource.java:52)
> 	at org.taktik.mpegts.sources.AbstractMTSSource.nextPacket(AbstractMTSSource.java:13)
> 	at org.taktik.mpegts.Streamer.fillBuffer(Streamer.java:267)
> 	at java.lang.Thread.run(Thread.java:748)

**Comment by nim56** [comment] 2018-11-23 17:33
I have encountered the same problem since 1.9.0

**Comment by 0xboobface** [comment] 2018-11-24 14:58
> java.nio.channels.ClosedByInterruptException: null

I think, this happens at the end of the stream and can be ignored.

> 2018-11-23 03:46:33,302 WARN [Thread-312] c.r.d.MergedHlsDownload [MergedHlsDownload.java:180] Missed segments 7537 < 7544 in download for http*

This isn't really an error and something, which can happen for HLS streaming. HLS works like this: The whole stream consists of many video files with a length of few seconds. A video player or ctbrec has to download these segments in order and play them / write them to a file. The server provides a playlist, which lists the next x segments. After these segments are processed by ctbrec, ctbrec has to fetch the playlist again to get the next bunch of segments. If the playlist didn't change ctbrec has to wait a bit and try again. It may now happen, that between fetching the old playlist and the new playlist too much time went by (for example because of network problems) and some segments are missed. In this case ctbrec tries to compensate by trying to download the segments anyways. This is what you see in your log.

> [BlockingMultiMTSSource.java:51] Failed to fix continuity. MTSPacket probably invalid

This also is not critical. ctbrec tries to write a valid MPEG TS file. If segments are missing, the video timestamps of the following segments are not correct anymore. ctbrec tries to fix that. This error can be ignored.

In a perfect world with perfect streams and network conditions you wouldn't see the last two errors.
The errors also are not related to the original problem.

Back to the original topic: Do you remember from which site the models where?

**Comment by nim56** [comment] 2018-11-24 20:41
I also have this problem since 1.9.0. I just did a test and it happened on MyFreeCams, BongaCams, Chaturbate and Cam4.

**Comment by LostSoul99** [comment] 2018-11-24 22:40
I had this issue as well on MFC and Chaturbate

**Comment by reyaz006** [comment] 2018-11-25 00:35
>Do you remember from which site the models were?

Chaturbate.

It really doesn't seem to be related to any events on a stream. I guess the internal process gets stuck and breaks after too many missing segments.

**Comment by nim56** [comment] 2018-11-26 15:23
Maybe it has something to do with the java version required since 1.9.0? I tried installing java 11 64bit but it didn't fix the problem, I haven't tried 1.11.0 though.

**Comment by nim56** [comment] 2018-11-26 20:14
I'm on windows 7 64bit if that makes a difference.

**Comment by 0xboobface** [comment] 2018-11-27 13:16
I might have found the problem, but this is hard to test. If one of you can easily reproduce this problem, let me know, how to do it. Also, if you notice the error occurring, please save the ctbrec.log and attach it here.

**Comment by nim56** [comment] 2018-11-27 14:12
I just started recording several models from each site and I check the videos from time to time by opening them twice in with 5 seconds in between, and if the time doesn't change and it still says that it is recording in ctbrec and the open in player function works it means that there was a problem. I will try to reproduce it and report the log.

**Comment by nim56** [comment] 2018-11-27 15:16
The problem started here:

`2018-11-27 16:01:52,636 WARN [Thread-168] c.r.d.MergedHlsDownload [MergedHlsDownload.java:180] Missed segments 5490 < 5491 in download for https://ded3885-edge9.bcrncdn.com/hls/stream_lindsay-ford/chunks.m3u8
2018-11-27 16:01:52,637 DEBUG [Thread-168] c.r.d.MergedHlsDownload [MergedHlsDownload.java:185] Loading missed segment 5490 for model https://ded3885-edge9.bcrncdn.com/hls/stream_lindsay-ford/chunks.m3u8
2018-11-27 16:01:53,056 DEBUG [Segment Merger Thread] c.r.d.MergedHlsDownload [MergedHlsDownload.java:288] Streamer finished
2018-11-27 16:02:09,310 WARN [Thread-168] c.r.d.MergedHlsDownload [MergedHlsDownload.java:180] Missed segments 5494 < 5504 in download for https://ded3885-edge9.bcrncdn.com/hls/stream_lindsay-ford/chunks.m3u8
2018-11-27 16:02:09,310 DEBUG [Thread-168] c.r.d.MergedHlsDownload [MergedHlsDownload.java:185] Loading missed segment 5494 for model https://ded3885-edge9.bcrncdn.com/hls/stream_lindsay-ford/chunks.m3u8
2018-11-27 16:02:09,773 DEBUG [Thread-168] c.r.d.MergedHlsDownload [MergedHlsDownload.java:185] Loading missed segment 5495 for model https://ded3885-edge9.bcrncdn.com/hls/stream_lindsay-ford/chunks.m3u8
2018-11-27 16:02:12,580 DEBUG [Thread-168] c.r.d.MergedHlsDownload [MergedHlsDownload.java:185] Loading missed segment 5496 for model https://ded3885-edge9.bcrncdn.com/hls/stream_lindsay-ford/chunks.m3u8
2018-11-27 16:02:15,335 DEBUG [Thread-168] c.r.d.MergedHlsDownload [MergedHlsDownload.java:185] Loading missed segment 5497 for model https://ded3885-edge9.bcrncdn.com/hls/stream_lindsay-ford/chunks.m3u8
`

**Comment by 0xboobface** [comment] 2018-11-27 15:20
Please check , if there is a log message "Download terminated for lindsay-ford". I guess, there isn't.

**Comment by nim56** [comment] 2018-11-27 15:32
Another model from MFC the download paused (bug) but there is nothing about it in the log, I'm pretty sure the open in player function wasn't working so I checked the site and she was online, but now after 5 minutes or so the open in player function is working but the download is still paused.

**Comment by nim56** [comment] 2018-11-27 15:41
I have the same kind of error messages on another model that went in a show but ctbrec says it is still recording.

**Comment by nim56** [comment] 2018-11-27 15:57
This model went offline but ctbrec says it is recording:

> 2018-11-27 16:01:47,780 DEBUG [OnlineMonitor] c.r.LocalRecorder [LocalRecorder.java:136] Starting recording for model sarah041516
2018-11-27 16:04:52,858 DEBUG [Thread-200] c.r.d.MergedHlsDownload [MergedHlsDownload.java:134] Download for sarah041516 terminated
2018-11-27 16:04:52,858 DEBUG [Segment Merger Thread] c.r.d.MergedHlsDownload [MergedHlsDownload.java:288] Streamer finished
2018-11-27 16:04:52,858 ERROR [Thread-200] c.r.LocalRecorder [LocalRecorder.java:166] Download for sarah041516 failed. Download alive: false
java.io.IOException: Couldn't download segment
	at ctbrec.recorder.download.MergedHlsDownload.start(MergedHlsDownload.java:128)
	at ctbrec.recorder.LocalRecorder$1.run(LocalRecorder.java:164)
Caused by: ctbrec.io.HttpException: 403 - 
	at ctbrec.recorder.download.AbstractHlsDownload.getNextSegments(AbstractHlsDownload.java:79)
	at ctbrec.recorder.download.MergedHlsDownload.downloadSegments(MergedHlsDownload.java:143)
	at ctbrec.recorder.download.MergedHlsDownload.start(MergedHlsDownload.java:116)
	... 1 common frames omitted
2018-11-27 16:04:53,063 DEBUG [ProcessMonitor] c.r.LocalRecorder [LocalRecorder.java:338] Recording terminated for model sarah041516
2018-11-27 16:05:11,047 DEBUG [Player stdout pipe] c.i.StreamRedirectThread [StreamRedirectThread.java:29] Stream redirect thread ended
2018-11-27 16:05:11,047 DEBUG [Player stderr pipe] c.i.StreamRedirectThread [StreamRedirectThread.java:29] Stream redirect thread ended
2018-11-27 16:05:11,054 DEBUG [ctbrec.ui.Player$PlayerThread] c.u.Player [Player.java:148] Media player finished.
2018-11-27 16:05:47,928 INFO [OnlineMonitor] c.r.LocalRecorder [LocalRecorder.java:418] Model sarah041516's room back to public. Starting recording
2018-11-27 16:05:47,928 DEBUG [OnlineMonitor] c.r.LocalRecorder [LocalRecorder.java:136] Starting recording for model sarah041516
2018-11-27 16:06:56,126 DEBUG [Thread-204] c.r.d.MergedHlsDownload [MergedHlsDownload.java:169] Playlist not found. Assuming model went offline
2018-11-27 16:06:56,126 DEBUG [Thread-204] c.r.d.MergedHlsDownload [MergedHlsDownload.java:134] Download for Goddess_Helen terminated
2018-11-27 16:06:56,127 DEBUG [Segment Merger Thread] c.r.d.MergedHlsDownload [MergedHlsDownload.java:288] Streamer finished
2018-11-27 16:06:56,424 DEBUG [ProcessMonitor] c.r.LocalRecorder [LocalRecorder.java:338] Recording terminated for model Goddess_Helen
2018-11-27 16:06:56,428 INFO [ProcessMonitor] c.r.LocalRecorder [LocalRecorder.java:311] Restarting recording for model Goddess_Helen
2018-11-27 16:06:56,428 DEBUG [ProcessMonitor] c.r.LocalRecorder [LocalRecorder.java:136] Starting recording for model Goddess_Helen
2018-11-27 16:06:59,090 WARN [Thread-231] c.r.d.MergedHlsDownload [MergedHlsDownload.java:180] Missed segments 45 < 46 in download for https://edge115.stream.highwebmedia.com/live-edge/amlst:sarah041516-sd-9be7e8801a0e345fb04e071824cdbc5921ea7d05e41d0a0615c61a6007823ab5_trns_h264/chunklist_w272764604_b818000.m3u8?rp=96d409a69086f91fdf2e0efc5bc560bb12779ee1b86084c914587323a0a0bb2d&u=dave211a&t=%7B%22username%22%3A%22dave211a%22%2C%22org%22%3A%22ASH%22%2C%22expire%22%3A1543331201%2C%22sig%22%3A%22999ceac888ed8ef506207f2ddf7f4de5292b38bfc5aad28604d1b1075e36c6c0%22%2C%22room%22%3A%22sarah041516%22%7D
2018-11-27 16:06:59,091 DEBUG [Thread-231] c.r.d.MergedHlsDownload [MergedHlsDownload.java:185] Loading missed segment 45 for model https://edge115.stream.highwebmedia.com/live-edge/amlst:sarah041516-sd-9be7e8801a0e345fb04e071824cdbc5921ea7d05e41d0a0615c61a6007823ab5_trns_h264/chunklist_w272764604_b818000.m3u8?rp=96d409a69086f91fdf2e0efc5bc560bb12779ee1b86084c914587323a0a0bb2d&u=dave211a&t=%7B%22username%22%3A%22dave211a%22%2C%22org%22%3A%22ASH%22%2C%22expire%22%3A1543331201%2C%22sig%22%3A%22999ceac888ed8ef506207f2ddf7f4de5292b38bfc5aad28604d1b1075e36c6c0%22%2C%22room%22%3A%22sarah041516%22%7D
2018-11-27 16:06:59,209 DEBUG [Segment Merger Thread] c.r.d.MergedHlsDownload [MergedHlsDownload.java:288] Streamer finished
2018-11-27 16:09:19,436 DEBUG [Thread-16] c.r.d.MergedHlsDownload [MergedHlsDownload.java:169] Playlist not found. Assuming model went offline

**Comment by nim56** [comment] 2018-11-27 16:07
another one (no download terminated) :

> 2018-11-27 16:02:00,513 WARN [Thread-192] c.r.d.MergedHlsDownload [MergedHlsDownload.java:180] Missed segments 3301 < 3303 in download for https://edge142.stream.highwebmedia.com/live-edge/amlst:vickiesweety-sd-4d665b82803bd23612818d130259df8b40415aaf869c45a81e30d04850668748_trns_h264/chunklist_w1717710598_b3096000.m3u8?rp=286c1f08ca43fa6fde3a667a033dff678112a72fdf4a01717ba1336d98da27c3&u=dave211a&t=%7B%22username%22%3A%22dave211a%22%2C%22org%22%3A%22SRB%22%2C%22expire%22%3A1543330959%2C%22sig%22%3A%224b2091b4e395148faff824eaff0d732e1b9cbd20220ad57a1a3d79dc56eea579%22%2C%22room%22%3A%22vickiesweety%22%7D
2018-11-27 16:02:00,514 DEBUG [Thread-192] c.r.d.MergedHlsDownload [MergedHlsDownload.java:185] Loading missed segment 3301 for model https://edge142.stream.highwebmedia.com/live-edge/amlst:vickiesweety-sd-4d665b82803bd23612818d130259df8b40415aaf869c45a81e30d04850668748_trns_h264/chunklist_w1717710598_b3096000.m3u8?rp=286c1f08ca43fa6fde3a667a033dff678112a72fdf4a01717ba1336d98da27c3&u=dave211a&t=%7B%22username%22%3A%22dave211a%22%2C%22org%22%3A%22SRB%22%2C%22expire%22%3A1543330959%2C%22sig%22%3A%224b2091b4e395148faff824eaff0d732e1b9cbd20220ad57a1a3d79dc56eea579%22%2C%22room%22%3A%22vickiesweety%22%7D
2018-11-27 16:02:06,268 DEBUG [Thread-192] c.r.d.MergedHlsDownload [MergedHlsDownload.java:185] Loading missed segment 3302 for model https://edge142.stream.highwebmedia.com/live-edge/amlst:vickiesweety-sd-4d665b82803bd23612818d130259df8b40415aaf869c45a81e30d04850668748_trns_h264/chunklist_w1717710598_b3096000.m3u8?rp=286c1f08ca43fa6fde3a667a033dff678112a72fdf4a01717ba1336d98da27c3&u=dave211a&t=%7B%22username%22%3A%22dave211a%22%2C%22org%22%3A%22SRB%22%2C%22expire%22%3A1543330959%2C%22sig%22%3A%224b2091b4e395148faff824eaff0d732e1b9cbd20220ad57a1a3d79dc56eea579%22%2C%22room%22%3A%22vickiesweety%22%7D
2018-11-27 16:02:16,158 WARN [Thread-192] c.r.d.MergedHlsDownload [MergedHlsDownload.java:180] Missed segments 3306 < 3311 in download for https://edge142.stream.highwebmedia.com/live-edge/amlst:vickiesweety-sd-4d665b82803bd23612818d130259df8b40415aaf869c45a81e30d04850668748_trns_h264/chunklist_w1717710598_b3096000.m3u8?rp=286c1f08ca43fa6fde3a667a033dff678112a72fdf4a01717ba1336d98da27c3&u=dave211a&t=%7B%22username%22%3A%22dave211a%22%2C%22org%22%3A%22SRB%22%2C%22expire%22%3A1543330959%2C%22sig%22%3A%224b2091b4e395148faff824eaff0d732e1b9cbd20220ad57a1a3d79dc56eea579%22%2C%22room%22%3A%22vickiesweety%22%7D
2018-11-27 16:02:16,158 DEBUG [Thread-192] c.r.d.MergedHlsDownload [MergedHlsDownload.java:185] Loading missed segment 3306 for model https://edge142.stream.highwebmedia.com/live-edge/amlst:vickiesweety-sd-4d665b82803bd23612818d130259df8b40415aaf869c45a81e30d04850668748_trns_h264/chunklist_w1717710598_b3096000.m3u8?rp=286c1f08ca43fa6fde3a667a033dff678112a72fdf4a01717ba1336d98da27c3&u=dave211a&t=%7B%22username%22%3A%22dave211a%22%2C%22org%22%3A%22SRB%22%2C%22expire%22%3A1543330959%2C%22sig%22%3A%224b2091b4e395148faff824eaff0d732e1b9cbd20220ad57a1a3d79dc56eea579%22%2C%22room%22%3A%22vickiesweety%22%7D

**Comment by nim56** [comment] 2018-11-28 19:58
Great job, I haven't had any problem so far.

**Comment by reyaz006** [comment] 2018-11-29 09:39
Trying new version. There is something new now:

> 2018-11-29 00:11:36,417 ERROR [Thread-43] c.r.LocalRecorder [LocalRecorder.java:177] Download for * failed. Download alive: false
> java.io.IOException: Couldn't parse stream information
> 	at ctbrec.recorder.download.MergedHlsDownload.start(MergedHlsDownload.java:140)
> 	at ctbrec.recorder.LocalRecorder$1.run(LocalRecorder.java:175)
> Caused by: com.iheartradio.m3u8.ParseException: invalid attribute name: EXT-X-STREAM-INF - #EXT-X-STREAM-INF:BANDWIDTH=488000,NAME="FPS:30.0",CODECS="avc1.42c015,mp4a.40.2",RESOLUTION=426x240
> 	at com.iheartradio.m3u8.ParseException.create(ParseException.java:35)
> 	at com.iheartradio.m3u8.ParseUtil.parseAttributes(ParseUtil.java:167)
> 	at com.iheartradio.m3u8.MasterPlaylistLineParser$3.parse(MasterPlaylistLineParser.java:270)
> 	at com.iheartradio.m3u8.ExtendedM3uParser.parse(ExtendedM3uParser.java:70)
> 	at com.iheartradio.m3u8.PlaylistParser.parse(PlaylistParser.java:115)
> 	at ctbrec.sites.chaturbate.Chaturbate.getMasterPlaylist(Chaturbate.java:328)
> 	at ctbrec.sites.chaturbate.Chaturbate.getMasterPlaylist(Chaturbate.java:318)
> 	at ctbrec.sites.chaturbate.ChaturbateModel.getMasterPlaylist(ChaturbateModel.java:93)
> 	at ctbrec.sites.chaturbate.ChaturbateModel.getStreamSources(ChaturbateModel.java:105)
> 	at ctbrec.recorder.download.AbstractHlsDownload.getSegmentPlaylistUrl(AbstractHlsDownload.java:86)
> 	at ctbrec.recorder.download.MergedHlsDownload.start(MergedHlsDownload.java:128)
> 	... 1 common frames omitted

I don't see that download interrupts now but I'm going to check later how good the video got recorded. The last time with older version it was very choppy with more than 50% duration lost.

**Comment by reyaz006** [comment] 2018-11-30 06:17
>This is unrelated to the new version. The playlist parser found an invalid attribute and complains about it. I have to set it to lenient mode. Then this error should go away.

I see. But just in case, I'm unable to switch resolution for that model because of this error.

**Closed** 2018-12-02 23:45 UTC
Labels: bug
