### ISSUE TITLE
Unable to view or download from server

### ISSUE THREAD

**Issue by bj73** [0xboobface/ctbrec#63] opened 2018-11-16 06:17 UTC
I'm running CTBRec 1.8.0 on:
Ubuntu 16.04 LTS (VPS) OpenJDK 8 headless
Debian 8 (VPS) OpenJDK 8
Raspberry Pi 2 DietPi v6.17.12 (LAN) OpenJDK 8 headless

All of them work fine for recording, I can access the servers remotely with CTBRec in client mode but on none of them can I view or download recorded video.

When I try to view it, VLC reports the following (IP and model name changed):
**Your input can't be opened:
VLC is unable to open the MRL 'http://x.x.x.x:33080/hls/somemodel/2018-11-16_00-21/playlist.m3u8'. Check the log for details.**

What is the **/hls** path being given, (captures are going to **/root/ctbrec/captures**) ?

If I try to download the video, CTBRec reports the following error:
**The recording could not be downloaded
An error occured: Couldn't parse stream information**

The playlists are being created properly as I can download all the files and use ffmpeg to create a single file, eg. _ffmpeg -i playlist.m3u8 -c:v copy -c:a copy output.mp4_

What exactly is needed at the server or client end to enable the viewing/downloading of the completed recordings?

_The following is the client log after trying to View and Download a recording:_
2018-11-16 16:40:02,329 ERROR [Download Thread somemodel/2018-11-16_00-21] streamer [Streamer.java:84] Couldn't interrupt streamer threads
2018-11-16 16:40:02,334 ERROR [Download Thread somemodel/2018-11-16_00-21] c.u.RecordingsTab [RecordingsTab.java:346] Error while downloading recording
java.io.IOException: Couldn't parse stream information
	at ctbrec.recorder.download.MergedHlsDownload.start(MergedHlsDownload.java:76)
	at ctbrec.ui.RecordingsTab$4.run(RecordingsTab.java:329)
Caused by: com.iheartradio.m3u8.ParseException: unable to determine playlist type: {"status": "error", "msg": "HMAC does not match"}
	at com.iheartradio.m3u8.ParseException.create(ParseException.java:35)
	at com.iheartradio.m3u8.ParseException.create(ParseException.java:16)
	at com.iheartradio.m3u8.ExtendedM3uParser.parse(ExtendedM3uParser.java:80)
	at com.iheartradio.m3u8.PlaylistParser.parse(PlaylistParser.java:115)
	at ctbrec.recorder.download.AbstractHlsDownload.getNextSegments(AbstractHlsDownload.java:59)
	at ctbrec.recorder.download.MergedHlsDownload.downloadSegments(MergedHlsDownload.java:143)
	at ctbrec.recorder.download.MergedHlsDownload.start(MergedHlsDownload.java:73)
	... 1 common frames omitted

_And this is the playlist that was generated at the end of the recording, (short test recording):_
#EXTM3U
#EXT-X-VERSION:4
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-TARGETDURATION:1
#EXT-X-MEDIA-SEQUENCE:0
#EXTINF:1.919,media_w937538976_b3096000_9926.ts
media_w937538976_b3096000_9926.ts
#EXTINF:1.917,media_w937538976_b3096000_9927.ts
media_w937538976_b3096000_9927.ts
#EXTINF:1.919,media_w937538976_b3096000_9928.ts
media_w937538976_b3096000_9928.ts
#EXTINF:1.919,media_w937538976_b3096000_9929.ts
media_w937538976_b3096000_9929.ts
#EXTINF:1.919,media_w937538976_b3096000_9930.ts
media_w937538976_b3096000_9930.ts
#EXTINF:1.919,media_w937538976_b3096000_9931.ts
media_w937538976_b3096000_9931.ts
#EXTINF:1.918,media_w937538976_b3096000_9932.ts
media_w937538976_b3096000_9932.ts
#EXTINF:2.378,media_w937538976_b3096000_9933.ts
media_w937538976_b3096000_9933.ts
#EXTINF:2.378,media_w937538976_b3096000_9934.ts
media_w937538976_b3096000_9934.ts
#EXTINF:1.959,media_w937538976_b3096000_9935.ts
media_w937538976_b3096000_9935.ts
#EXTINF:1.919,media_w937538976_b3096000_9936.ts
media_w937538976_b3096000_9936.ts
#EXTINF:1.919,media_w937538976_b3096000_9937.ts
media_w937538976_b3096000_9937.ts
#EXTINF:1.919,media_w937538976_b3096000_9938.ts
media_w937538976_b3096000_9938.ts
#EXTINF:1.919,media_w937538976_b3096000_9939.ts
media_w937538976_b3096000_9939.ts
#EXTINF:1.918,media_w937538976_b3096000_9940.ts
media_w937538976_b3096000_9940.ts
#EXTINF:1.919,media_w937538976_b3096000_9941.ts
media_w937538976_b3096000_9941.ts
#EXT-X-ENDLIST

**Comment by 0xboobface** [comment] 2018-11-16 10:57
> {"status": "error", "msg": "HMAC does not match"}

You have the HMAC authentication enabled. That's definitely the cause of the problems. I'm not using that and I haven't tested that thoroughly. That's why there might be some bugs :grin: 
I will do some testing and see, if I can solve those problems. For the time being, try to remove the "key" entry from the server.json in ~/.config/ctbrec. After a restart of the server, things should work. But be aware that you are disabled the authentication by doing that.

**Comment by 0xboobface** [comment] 2018-11-16 11:57
Fixed in 25d5fa9646b33286e56c5f32e71c88bfe81f82ce

**Comment by bj73** [comment] 2018-11-16 23:53
Thanks you.

I'm guessing that the server end will need to be upgraded to >1.9.0 which kind of screws up running it on a Raspberry Pi ?

**Comment by 0xboobface** [comment] 2018-11-17 01:02
> which kind of screws up running it on a Raspberry Pi ?

Why? 
Do you need the HMAC authentication?

**Comment by bj73** [comment] 2018-11-17 03:09
I was going to open a port through the router for remote connection to it, would have been nice to have some kind of authentication.

Could have used port knocking but unfortunately my ISP supplied router doesn't have that facility.

**Comment by 0xboobface** [comment] 2018-11-17 11:18
> I was going to open a port through the router for remote connection to it, would have been nice to have some kind of authentication.

OK, you need the hmac auth, but why can you not upgrade to >1.9.0 on the pi?

**Comment by bj73** [comment] 2018-11-17 23:16
RasPi distros are 32bit, there's only one or two that are 64bit, (you mention it's a requirement with >1.9.0), and they're experimental.

**Comment by 0xboobface** [comment] 2018-11-18 11:54
Technically the 64-bit dependency comes from JavaFX (the graphical interface). I could split the project up in client and server and build the server for older versions of Java and then also 32-bit would be supported.

**Comment by bj73** [comment] 2018-11-19 04:30
The machines I'm running it on as servers are all headless so it would be fantastic if the server side could be split off but only if it isn't too much trouble.

I've just ordered a RasPi 3B+ which is capable of 64bit so I can start experimenting otherwise.

**Comment by 0xboobface** [comment] 2018-11-19 18:13
Check out the server bundle from the lastest release 1.10.0. It should run with Java 1.8 32-bit

**Closed by 0xboobface** 2018-11-19 18:13 UTC

**Comment by bj73** [comment] 2018-11-20 06:42
Thank you, working great on the RasPi (with HMAC enabled).
