### ISSUE TITLE
Playlist parsing exception

### ISSUE THREAD

**Issue by tvasenin** [0xboobface/ctbrec#92] opened 2018-12-02 17:10 UTC
```
ERROR ctbrec.recorder.LocalRecorder - Download for ******** failed. Download alive: false
java.io.IOException: Couldn't parse HLS playlist:
#EXTM3U
#EXT-X-VERSION:4
#EXT-X-STREAM-INF:BANDWIDTH=356000,NAME="FPS:30.0",CODECS="avc1.42c00d,mp4a.40.2",RESOLUTION=320x240

        at ctbrec.recorder.download.HlsDownload.start(HlsDownload.java:114)
        at ctbrec.recorder.LocalRecorder$1.run(LocalRecorder.java:176)
Caused by: com.iheartradio.m3u8.ParseException: invalid attribute name: EXT-X-STREAM-INF - #EXT-X-STREAM-INF:BANDWIDTH=356000,NAME="FPS:30.0",CODECS="avc1.42c00d,mp4a.40.2",RESOLUTION=320x240
        at com.iheartradio.m3u8.ParseException.create(ParseException.java:35)
        at com.iheartradio.m3u8.ParseUtil.parseAttributes(ParseUtil.java:167)
        at com.iheartradio.m3u8.MasterPlaylistLineParser$3.parse(MasterPlaylistLineParser.java:270)
        at com.iheartradio.m3u8.ExtendedM3uParser.parse(ExtendedM3uParser.java:70)
        at com.iheartradio.m3u8.PlaylistParser.parse(PlaylistParser.java:115)
        at ctbrec.sites.chaturbate.Chaturbate.getMasterPlaylist(Chaturbate.java:328)
        at ctbrec.sites.chaturbate.Chaturbate.getMasterPlaylist(Chaturbate.java:318)
        at ctbrec.sites.chaturbate.ChaturbateModel.getMasterPlaylist(ChaturbateModel.java:93)
        at ctbrec.sites.chaturbate.ChaturbateModel.getStreamSources(ChaturbateModel.java:105)
        at ctbrec.recorder.download.AbstractHlsDownload.getSegmentPlaylistUrl(AbstractHlsDownload.java:86)
        at ctbrec.recorder.download.HlsDownload.start(HlsDownload.java:57)
        ... 1 common frames omitted
```
v1.11.0 throws this exception once in a minute, but is still able to download.
v1.12.1 throws it each second, and restarts download each time (nothing is downloaded).

**Comment by 0xboobface** [comment] 2018-12-02 18:48
Duplicate of #87

**Closed by 0xboobface** 2018-12-02 18:48 UTC
Labels: duplicate
